add_rules("mode.debug","mode.release")
--add_requires("eigen >=3.4.0")
target("flex-demo")
    add_rules("plugin.vsxmake.autoupdate")
    add_defines("WIN64")

    set_kind("binary")
    add_includedirs(".",{public=true})
    add_headerfiles("(./*.h)")
    add_includedirs("scenes",{public=true})
    add_headerfiles("(scenes/*.h)")
    add_includedirs("opengl",{public=true})
    add_headerfiles("(opengl/*.h)")
    add_includedirs("(../include)",{public=true})
    add_headerfiles("(../include/*.h)")
    add_includedirs("(../core)",{public=true})
    add_headerfiles("(../core/*.h)")

    add_files("*.cpp","*.cu","*.cxx","*.cc")
    add_files("../core/*.cpp")

    add_includedirs("../external/SDL2-2.0.4/include",{public=true})
    add_headerfiles("../external/SDL2-2.0.4/include/*.h")
    add_files("../external/SDL2-2.0.4/lib/x64/*.lib")

    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_cuflags("-Xcompiler /bigobj")
    --add_packages("eigen",{public=true})
